<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Bayan.Editor.WinForms</AssemblyName>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Bayan.Compiler.Core/Bayan.Compiler.Core.csproj" />
    <ProjectReference Include="../Bayan.Compiler.Cli/Bayan.Compiler.Cli.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="CopyCompilerCliArtifacts" AfterTargets="Build">
    <ItemGroup>
      <CompilerCliArtifacts Include="$(MSBuildProjectDirectory)\..\Bayan.Compiler.Cli\bin\$(Configuration)\net6.0\Bayan.Compiler.Cli.*" />
      <CompilerCoreArtifact Include="$(MSBuildProjectDirectory)\..\Bayan.Compiler.Core\bin\$(Configuration)\net6.0\Bayan.Compiler.Core.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(CompilerCliArtifacts);@(CompilerCoreArtifact)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>
</Project>
